### ISSUE TITLE
ruCombine error with mutate()

### ISSUE THREAD

**Issue by cembrowskilab** [kaitsull/RUHi#1]
Hey Kaitlin! 

The ruCombine() function gives an error when I try to combine 3 data tables all read using the ruRead() function - "Error in UseMethod("mutate"): no applicable method for 'mutate' applied to an object of class "c('double', 'numeric')" 

I'm guessing it might have something to do with the metadata columns? I have region, anum, and section filled in for each of the 3 tables. 

Screenshot of script + console: 
<img width="904" alt="Screen Shot 2022-10-25 at 15 36 11" src="https://user-images.githubusercontent.com/101438669/197895965-854b0ac3-028b-4506-ae79-a90e983975cf.png">

Screenshot of console when I run `glimpse(ATN_1)`
<img width="878" alt="Screen Shot 2022-10-25 at 15 49 19" src="https://user-images.githubusercontent.com/101438669/197896595-b637e70e-d8fd-4c28-81f6-3a0118db94ed.png">

Thanks sm!! :)

**Comment by kaitsull** [comment]
Hey Angela, thanks for posting.

The function takes a *list* of data frames, not a *vector*.
The issue here is that you are using the `c()` function and not the `list()` function within `ruCombine()`

You can check out the instructions in the `README.md` file or use `help(ruCombine)` in the future to see arguments for each function. 😸 

(Also in the future if you can open issues on the forked repo on our lab's GitHub only that would be super helpful!)
